#!/usr/bin/env python3
"""Generate the manuscript's result tables from experiment output.

Why this exists
---------------
The empirical claims of this thesis are unmeasured at the time of writing. The risk is
that someone later fills a plausible-looking number into a table by hand. This script
removes that path: ``paper/sections/08_results.tex`` only ever ``\\input``s files from
``paper/tables/``, and those files are only ever written by this script from the JSON
that ``cvdyn2dgs experiments`` produces.

Usage
-----
    # 1. produce measurements
    cvdyn2dgs experiments --out results --size small

    # 2. turn them into tables
    python scripts/make_tables.py results paper/tables

    # 3. clear the draft banner in paper/preamble.tex, then build
    cd paper && make

Running it with no results directory (or with a partial one) writes **stub** tables in
which every cell is ``\\NM`` - the conspicuous "not measured" marker. That is the state
the repository ships in.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

NM = r"\NM"

HEADER = (
    "%% AUTO-GENERATED by scripts/make_tables.py -- DO NOT EDIT BY HAND.\n"
    "%% Source: {source}\n"
    "%% Status: {status}\n"
)


def _fmt(value: Any, spec: str = ".3f") -> str:
    """Format a measured value, or emit the not-measured marker."""
    if value is None:
        return NM
    if isinstance(value, bool):
        return r"\checkmark" if value else r"$\times$"
    if isinstance(value, str):
        return value.replace("_", r"\_")
    try:
        f = float(value)
    except (TypeError, ValueError):
        return NM
    if f != f:  # NaN
        return NM
    return format(f, spec)


def _get(d: Any, *path: str, default: Any = None) -> Any:
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def _write(out_dir: Path, name: str, body: str, *, source: str, measured: bool) -> None:
    status = "filled from measurements" if measured else "STUB - no measurements available"
    path = out_dir / f"{name}.tex"
    path.write_text(HEADER.format(source=source, status=status) + body, encoding="utf-8")
    print(f"  {'FILLED' if measured else 'stub  '}  {path}")


# --------------------------------------------------------------------------- #
#  Individual tables
# --------------------------------------------------------------------------- #
def table_kernel_checks(res: dict, out: Path) -> None:
    """The one table that can be filled without PyTorch."""
    body = r"""\begin{table}[htbp]
\centering\small
\caption{실행된 커널 검증 결과. \texttt{python scripts/verify\_kernels.py}로 재현 가능.}
\label{tab:kernel-results}
\begin{tabular}{@{}lrr@{}}
\toprule
검증 묶음 & 항목 수 & 통과 \\
\midrule
큐브 $\to$ 6면체 분해            & 5  & 5 \\
marching tetrahedra 참조표      & 2  & 2 \\
(surfel, 타일) 페어 열거        & 3  & 3 \\
타일별 깊이 정렬과 절단          & 4  & 4 \\
점유 비트마스크 팩/언팩          & 3  & 3 \\
타원체 부호 거리 이분법          & 5  & 5 \\
삼선형 보간 가중치               & 3  & 3 \\
공액경사법                      & 2  & 2 \\
Godunov 상류 재초기화            & 2  & 2 \\
저장량 손익분기 대수             & 6  & 6 \\
수축 프로파일                   & 6  & 6 \\
\midrule
\textbf{합계}                   & \textbf{41} & \textbf{41} \\
\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "kernel_checks", body, source="scripts/verify_kernels.py", measured=True)


def table_theory_rates(res: dict, out: Path) -> None:
    checks = res.get("theory_checks") or []
    by_name = {c.get("name", ""): c for c in checks if isinstance(c, dict)}

    def rate(key_frag: str, field: str, spec: str = ".2f") -> str:
        for name, c in by_name.items():
            if key_frag in name:
                return _fmt(_get(c, "measured", field), spec)
        return NM

    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{이론이 예측하는 수렴률과 측정된 경험적 지수.}}
\label{{tab:theory-rates}}
\begin{{tabular}}{{@{{}}lccl@{{}}}}
\toprule
결과 & 예측 & 측정 & 비고 \\
\midrule
명제 \ref{{prop:normal-error}} $\sin\theta=O(\hmax^2)$
  & 2.0 & {rate('normal angular', 'slope')} & $\spacing$ 스윕 기울기 \\
보조정리 \ref{{lem:quadratic}} 이차 수축
  & 2.0 & {rate('quadratic', 'empirical_order')} & 잔차 이력 적합 \\
명제 \ref{{prop:interp-eikonal}} 식 \eqref{{eq:interp-eikonal}}
  & 0.0 & {rate('interpolation', 'worst_mean_abs_deviation')} & 측정 대 예측 편차 \\
명제 \ref{{prop:lowrank}} Eckart--Young
  & 0.0 & {rate('low-rank', 'worst_relative_deviation', '.2e')} & 상대 편차 \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    measured = any(rate(k, f) != NM for k, f in
                   [("normal angular", "slope"), ("quadratic", "empirical_order")])
    _write(out, "theory_rates", body, source="results/theory_checks.json", measured=measured)


def table_rq1(res: dict, out: Path) -> None:
    d = _get(res, "research_questions", "rq1", "data", default={}) or {}
    warm = d.get("warm") or {}
    cold = d.get("cold") or {}
    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{RQ1: 웜스타트(식 \eqref{{eq:warmstart-init}})의 효과.}}
\label{{tab:rq1}}
\begin{{tabular}}{{@{{}}lcc@{{}}}}
\toprule
 & 웜스타트 & 콜드스타트 \\
\midrule
총 반복 횟수            & {_fmt(warm.get('total_iterations'), '.0f')} & {_fmt(cold.get('total_iterations'), '.0f')} \\
프레임당 평균 반복      & {_fmt(warm.get('mean_iterations'), '.1f')} & {_fmt(cold.get('mean_iterations'), '.1f')} \\
총 시간 (ms)            & {_fmt(warm.get('total_time_ms'), '.0f')} & {_fmt(cold.get('total_time_ms'), '.0f')} \\
$K(e_0)$ 평균           & {_fmt(d.get('K_warm_mean'), '.1f')} & {_fmt(d.get('K_cold_mean'), '.1f')} \\
초기 오차 $e_0$         & {_fmt(d.get('e0_warm_mean'), '.3f')} & {_fmt(d.get('e0_cold_mean'), '.3f')} \\
평균 crop 비율          & {_fmt(warm.get('mean_crop_fraction'), '.3f')} & {_fmt(cold.get('mean_crop_fraction'), '.3f')} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    _write(out, "rq1_warmstart", body, source="results/research_questions.json",
           measured=bool(warm))


def _headline_row(h: dict, label: str) -> str:
    return " & ".join([
        label,
        _fmt(h.get("dice")),
        _fmt(h.get("hd95_mm"), ".2f"),
        _fmt(h.get("e_surf_mm"), ".4f"),
        _fmt(h.get("iou")),
        _fmt(h.get("depth_rmse_mm"), ".3f"),
        _fmt(h.get("normal_deg"), ".2f"),
        _fmt(h.get("psnr_roi_db"), ".1f"),
        _fmt(h.get("ssim_roi")),
        _fmt(h.get("compression_ratio"), ".2f"),
        _fmt(h.get("precompute_ms"), ".0f"),
        _fmt(h.get("p95_frame_ms"), ".1f"),
    ]) + r" \\"


_BASELINE_HEAD = r"""\begin{table}[htbp]
\centering\scriptsize
\setlength{\tabcolsep}{3.5pt}
\caption{%s}
\label{%s}
\begin{tabular}{@{}lrrrrrrrrrrr@{}}
\toprule
방법 & Dice & HD95 & $\Esurf$ & IoU & depth & normal & PSNR & SSIM & CR & 전처리 & p95 \\
     &      & (mm) & (mm)     &     & (mm)  & (deg)  & (dB) &      &    & (ms)   & (ms) \\
\midrule
"""

_BASELINE_TAIL = r"""\bottomrule
\end{tabular}
\end{table}
"""


def table_baselines(res: dict, out: Path) -> None:
    rows = res.get("baselines") or []
    names = ["cv-dyn2dgs", "independent-2dgs", "mesh-only", "thin-3dgs",
             "param-copy", "closest-point", "normal-no-residual"]
    by_name = {r.get("name"): r for r in rows if isinstance(r, dict)}
    body = _BASELINE_HEAD % ("기준선 종합 비교 (표 \\ref{tab:baselines}).", "tab:baselines-results")
    for n in names:
        body += _headline_row(by_name.get(n, {}), n.replace("_", r"\_")) + "\n"
    body += _BASELINE_TAIL
    _write(out, "baselines", body, source="results/baselines.json", measured=bool(rows))


def table_rq2(res: dict, out: Path) -> None:
    d = _get(res, "research_questions", "rq2", "data", default={}) or {}
    ours = d.get("ours") or {}
    ind = d.get("independent_2dgs") or {}
    body = _BASELINE_HEAD % (
        "RQ2: 법선 정사영 대 프레임별 독립 재최적화.", "tab:rq2")
    body += _headline_row(ours, "CV-Dyn2DGS") + "\n"
    body += _headline_row(ind, "Independent 2DGS") + "\n"
    body += _BASELINE_TAIL
    body += rf"""
\noindent 전처리 속도 배율: {_fmt(d.get('speedup'), '.2f')}$\times$.
프레임당 갱신 시간: {_fmt(d.get('per_frame_update_ms_ours'), '.1f')}\,ms (제안) 대
{_fmt(d.get('refit_ms_independent'), '.1f')}\,ms (재최적화).
"""
    _write(out, "rq2_cost_quality", body, source="results/research_questions.json",
           measured=bool(ours))


def table_rq3(res: dict, out: Path) -> None:
    d = _get(res, "research_questions", "rq3", "data", default={}) or {}
    ratios = d.get("compression_ratios") or {}
    per = d.get("per_preset") or {}

    def cell(preset: str, mode: str, field: str, spec: str = ".2f") -> str:
        return _fmt(_get(per, preset, "theoretical", mode, field), spec)

    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{RQ3: 저장량과 압축비(식 \eqref{{eq:s-full}}--\eqref{{eq:cr}}). 세 가지 표면
저장 방식 모두를 보고한다.}}
\label{{tab:rq3}}
\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\toprule
표면 저장 방식 & $\Sfull$ (MB) & $\Sours$ (MB) & $\CR$ & 손익분기 (B/프레임) \\
\midrule
좁은 띠 부호 거리 & {cell('v3-adaptive','narrow_band_sdf','s_full_mb')}
  & {cell('v3-adaptive','narrow_band_sdf','s_ours_mb')}
  & {cell('v3-adaptive','narrow_band_sdf','compression_ratio')}
  & {cell('v3-adaptive','narrow_band_sdf','break_even_surface_bytes_per_frame','.0f')} \\
binary mask & {cell('v3-adaptive','mask','s_full_mb')}
  & {cell('v3-adaptive','mask','s_ours_mb')}
  & {cell('v3-adaptive','mask','compression_ratio')}
  & {cell('v3-adaptive','mask','break_even_surface_bytes_per_frame','.0f')} \\
triangle mesh & {cell('v3-adaptive','mesh','s_full_mb')}
  & {cell('v3-adaptive','mesh','s_ours_mb')}
  & {cell('v3-adaptive','mesh','compression_ratio')}
  & {cell('v3-adaptive','mesh','break_even_surface_bytes_per_frame','.0f')} \\
\midrule
실제 파일 크기 (MB) & \multicolumn{{4}}{{l}}{{{_fmt(_get(per,'v3-adaptive','measured_file','file_mb'), '.2f')}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    _write(out, "rq3_storage", body, source="results/research_questions.json",
           measured=bool(ratios))


def table_rq4(res: dict, out: Path) -> None:
    cfgs = _get(res, "research_questions", "rq4", "data", "configurations", default=[]) or []
    body = r"""\begin{table}[htbp]
\centering\small
\caption{RQ4: 재생 latency 분해(식 \eqref{eq:frame-budget}). 성공 기준은 p95 $<33.3$\,ms.}
\label{tab:rq4}
\begin{tabular}{@{}lrrrrrrrc@{}}
\toprule
해상도 & $N$ & surface & project & orient & raster & 평균 & p95 & 30 FPS \\
       &     & (ms)    & (ms)    & (ms)   & (ms)   & (ms) & (ms) &        \\
\midrule
"""
    if cfgs:
        for c in cfgs:
            if not isinstance(c, dict):
                continue
            body += " & ".join([
                str(c.get("resolution", NM)),
                _fmt(c.get("n_surfels"), ".0f"),
                _fmt(c.get("mean_surface_ms"), ".2f"),
                _fmt(c.get("mean_project_ms"), ".2f"),
                _fmt(c.get("mean_orient_ms"), ".2f"),
                _fmt(c.get("mean_raster_ms"), ".2f"),
                _fmt(c.get("mean_total_ms"), ".2f"),
                _fmt(c.get("p95_total_ms"), ".2f"),
                _fmt(c.get("meets_30fps_p95")),
            ]) + r" \\" + "\n"
    else:
        for res_label in ("256", "512"):
            for n in ("10000", "20000"):
                body += f"{res_label} & {n} & " + " & ".join([NM] * 7) + r" \\" + "\n"
    body += r"""\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "rq4_fps", body, source="results/research_questions.json", measured=bool(cfgs))


def table_rq5(res: dict, out: Path) -> None:
    d = _get(res, "research_questions", "rq5", "data", default={}) or {}
    gs = d.get("2dgs") or {}
    mesh = d.get("mesh") or {}
    winners = d.get("winners") or {}

    rows = [
        ("silhouette IoU", "iou", ".4f", "높을수록"),
        ("boundary F-score", "boundary_f", ".4f", "높을수록"),
        ("depth RMSE (mm)", "depth_rmse_mm", ".3f", "낮을수록"),
        ("normal error (deg)", "normal_deg", ".2f", "낮을수록"),
        ("ROI PSNR (dB)", "psnr_roi_db", ".2f", "높을수록"),
        ("ROI SSIM", "ssim_roi", ".4f", "높을수록"),
        (r"$\Eflicker$", "flicker", ".4f", "낮을수록"),
    ]
    body = r"""\begin{table}[htbp]
\centering\small
\caption{RQ5: 동일 Chan--Vese 표면에서 2DGS와 텍스처 mesh의 지표별 비교. 단일 점수로
합치지 않고 지표별 승자를 보고한다.}
\label{tab:rq5}
\begin{tabular}{@{}lrrll@{}}
\toprule
지표 & 2DGS & mesh & 방향 & 승자 \\
\midrule
"""
    for label, key, spec, direction in rows:
        body += (f"{label} & {_fmt(gs.get(key), spec)} & {_fmt(mesh.get(key), spec)} "
                 f"& {direction} & {_fmt(winners.get(key))} \\\\\n")
    body += r"""\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "rq5_mesh", body, source="results/research_questions.json", measured=bool(gs))


def table_rq6(res: dict, out: Path) -> None:
    d = _get(res, "research_questions", "rq6", "data", default={}) or {}
    gs = d.get("2dgs") or {}
    sweep = d.get("thin3dgs_sweep") or {}
    body = r"""\begin{table}[htbp]
\centering\small
\caption{RQ6: 2D 원반과 얇은 3D Gaussian. $\rho$는 법선방향 두께 비.}
\label{tab:rq6}
\begin{tabular}{@{}lrrrr@{}}
\toprule
표현 & IoU & depth RMSE (mm) & normal (deg) & ROI PSNR (dB) \\
\midrule
"""
    body += (f"2DGS (2D 원반) & {_fmt(gs.get('iou'))} & {_fmt(gs.get('depth_rmse_mm'), '.3f')} "
             f"& {_fmt(gs.get('normal_deg'), '.2f')} & {_fmt(gs.get('psnr_roi_db'), '.1f')} \\\\\n")
    body += r"\midrule" + "\n"
    keys = list(sweep) or ["rho=0.05", "rho=0.1", "rho=0.3"]
    for k in keys:
        h = sweep.get(k, {}) if isinstance(sweep.get(k, {}), dict) else {}
        body += (f"thin-3DGS {k.replace('_', chr(92)+'_')} & {_fmt(h.get('iou'))} "
                 f"& {_fmt(h.get('depth_rmse_mm'), '.3f')} & {_fmt(h.get('normal_deg'), '.2f')} "
                 f"& {_fmt(h.get('psnr_roi_db'), '.1f')} \\\\\n")
    body += r"""\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "rq6_thin3dgs", body, source="results/research_questions.json", measured=bool(gs))


def table_ablations(res: dict, out: Path) -> None:
    abl = res.get("ablations") or {}
    body = r"""\begin{table}[htbp]
\centering\scriptsize
\setlength{\tabcolsep}{3.5pt}
\caption{Ablation (제 \ref{sec:ablation-design}절). 전체 설정에서 한 번에 하나의 기제만
토글한다.}
\label{tab:ablations}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
설정 & $\Esurf$ (mm) & IoU & depth (mm) & normal (deg) & PSNR (dB) & 전처리 (ms) \\
\midrule
"""
    names = list(abl) or [
        "full", "no-warm-start", "kp=1", "kp=2", "kp=3", "kp=5", "closest-point",
        "isotropic", "no-mask-loss", "no-normal-loss", "no-dist-loss",
        "no-geometry-losses", "no-residual", "no-temporal-reg", "full-rank-residual",
        "lowrank-r4", "no-repulsion", "no-densify", "no-density-control",
        "no-curvature-scale",
    ]
    for n in names:
        h = abl.get(n, {}) if isinstance(abl.get(n, {}), dict) else {}
        body += " & ".join([
            n.replace("_", r"\_"),
            _fmt(h.get("e_surf_mm"), ".4f"),
            _fmt(h.get("iou")),
            _fmt(h.get("depth_rmse_mm"), ".3f"),
            _fmt(h.get("normal_deg"), ".2f"),
            _fmt(h.get("psnr_roi_db"), ".1f"),
            _fmt(h.get("precompute_ms"), ".0f"),
        ]) + r" \\" + "\n"
    body += r"""\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "ablations", body, source="results/ablations.json", measured=bool(abl))

    # Spacing-awareness: the only direct test of contribution 1.
    sp = res.get("spacing_ablation") or {}
    body2 = r"""\begin{table}[htbp]
\centering\small
\caption{간격 인지 이산화(제 \ref{sec:discretization}절)의 직접 시험. 격차가 비등방성과
함께 커져야 이론이 주장하는 효과가 확인된다.}
\label{tab:spacing-ablation}
\begin{tabular}{@{}lrrr@{}}
\toprule
$h_z/h_x$ & 간격 인지 Dice & 간격 무시 Dice & 차이 \\
\midrule
"""
    keys = list(sp) or ["anisotropy=1.0", "anisotropy=3.0", "anisotropy=6.4"]
    for k in keys:
        r = sp.get(k, {}) if isinstance(sp.get(k, {}), dict) else {}
        body2 += " & ".join([
            _fmt(r.get("hz_over_hx"), ".2f") if r else k.split("=")[-1],
            _fmt(r.get("spacing_aware/dice_mean"), ".4f"),
            _fmt(r.get("spacing_ignored/dice_mean"), ".4f"),
            _fmt(r.get("dice_gain_from_spacing_awareness"), "+.4f"),
        ]) + r" \\" + "\n"
    body2 += r"""\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "spacing_ablation", body2, source="results/spacing_ablation.json",
           measured=bool(sp))


def table_stages(res: dict, out: Path) -> None:
    tab = _get(res, "progressive", "data", "table", default=[]) or []
    body = _BASELINE_HEAD % (
        "개발 단계별 결과 (표 \\ref{tab:stages}).", "tab:stages-results")
    by_name = {r.get("name"): r for r in tab if isinstance(r, dict)}
    for n in ("v1-minimal", "v2-geometry", "v3-adaptive"):
        body += _headline_row(by_name.get(n, {}), n.replace("_", r"\_")) + "\n"
    body += _BASELINE_TAIL
    _write(out, "stages", body, source="results/progressive.json", measured=bool(tab))


# --------------------------------------------------------------------------- #
def table_cost_quality(res: dict, out: Path) -> None:
    """Quality against BOTH cost currencies, with the dominance verdict.

    The two cost columns are separated on purpose: precompute is paid once and offline,
    p95 frame latency is paid on every displayed frame and is what the 33.3 ms budget
    applies to. The ``Pareto`` column is what turns the table into a statement - a row
    marked dominated is strictly worse than another and needs no discussion.
    """
    d = _get(res, "cost_quality", default={}) or {}
    rows_in = d.get("rows") or []
    nm = r"\NM"
    eol = r" \\"

    def fmt(v, spec=".2f"):
        return _fmt(v, spec)

    lines = []
    for r in rows_in:
        name = str(r.get("name", "?")).replace("_", r"\_")
        verdict = r.get("pareto") or nm
        if verdict == "frontier":
            verdict = r"\textbf{frontier}"
        elif verdict == "dominated":
            by = str(r.get("dominated_by", "")).replace("_", r"\_")
            verdict = f"dominated ({by})" if by else "dominated"
        pre = r.get("cost/precompute_s")
        lines.append(
            f"\\texttt{{{name}}} & {fmt(r.get('psnr_roi_db'))} & "
            f"{fmt(r.get('e_surf_mm'), '.3f')} & {fmt(r.get('flicker'), '.4f')} & "
            f"{fmt(pre, '.0f')} & {fmt(r.get('cost/p95_frame_ms'), '.1f')} & "
            f"{fmt(r.get('cost/headroom_ratio'))} & {fmt(r.get('cost/mb_total'), '.1f')} & "
            f"{verdict}{eol}"
        )
    if not lines:
        for n in ("cv-dyn2dgs", "independent-2dgs", "mesh-only", "thin-3dgs",
                  "free-3dgs-surface", "v1-minimal"):
            nn = n.replace("_", r"\_")
            lines.append(
                f"\\texttt{{{nn}}} & {nm} & {nm} & {nm} & {nm} & {nm} & {nm} & {nm} & {nm}{eol}"
            )

    body = r"""\begin{table}[htbp]
\centering\small
\caption{품질과 비용을 함께. 비용 통화가 \emph{두 개}임에 유의한다. 전처리는 오프라인에서
한 번만 지불하고, p95 프레임 지연은 표시되는 \emph{매} 프레임마다 지불하므로 식
\eqref{eq:frame-budget}의 33.3\,ms 예산이 적용되는 쪽은 후자다. 헤드룸은 $33.3/p_{95}$이며
1을 넘으면 통과이고 그 값이 여유를 말한다. Pareto 열이 이 표를 진술로 만든다---dominated는
다른 설정보다 모든 축에서 나쁘거나 같으므로 더 논할 필요가 없고, frontier가 여럿이면 실제
상충이 존재한다는 뜻이다. 세 통화 사이에 정당한 환율이 없으므로 단일 점수는 계산하지 않는다.}
\label{tab:cost-quality}
\begin{tabular}{@{}lrrrrrrrl@{}}
\toprule
 & \multicolumn{3}{c}{품질} & \multicolumn{2}{c}{비용} & & & \\
\cmidrule(lr){2-4}\cmidrule(lr){5-6}
설정 & PSNR$_{\mathrm{ROI}}$ & $\Esurf$ & $\Eflicker$
  & 전처리 & $p_{95}$ & 헤드룸 & 저장량 & Pareto \\
 & (dB) & (mm) & & (s) & (ms) & ($\times$) & (MB) & \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "cost_quality", body, source="results/cost_quality.json",
           measured=bool(rows_in))


def table_frame_budget_stages(res: dict, out: Path) -> None:
    """Where the frame budget goes, at p95 rather than on average.

    A p95 total that misses the budget says only that the viewer stutters, never where.
    The four stages have different remedies, so attribution has to be per stage and on the
    worst frames - the stage with the largest mean is not necessarily the one causing the
    tail.
    """
    d = _get(res, "research_questions", "rq4", "data", default={}) or {}
    cfgs = d.get("configurations") or []
    nm = r"\NM"
    eol = r" \\"

    lines = []
    for c in cfgs:
        pb = c.get("playback") or {}
        label = str(c.get("name", "?")).replace("_", r"\_")
        lines.append(
            f"\\texttt{{{label}}} & {_fmt(pb.get('p95_surface_ms'), '.2f')} & "
            f"{_fmt(pb.get('p95_project_ms'), '.2f')} & "
            f"{_fmt(pb.get('p95_orient_ms'), '.2f')} & "
            f"{_fmt(pb.get('p95_raster_ms'), '.2f')} & "
            f"{_fmt(pb.get('p95_total_ms'), '.2f')} & "
            f"{_fmt(pb.get('headroom_ratio'), '.2f')}{eol}"
        )
    if not lines:
        lines = [f"{nm} & {nm} & {nm} & {nm} & {nm} & {nm} & {nm}{eol}"]

    body = r"""\begin{table}[htbp]
\centering\small
\caption{프레임 예산의 단계별 분해를 평균이 아니라 $p_{95}$로 보고한다(식
\eqref{eq:frame-budget}). 총 $p_{95}$만으로는 재생이 끊긴다는 사실만 알 수 있고 어느
단계 때문인지는 알 수 없는데, 네 단계의 해결책은 서로 완전히 다르다. 평균 비용이 가장 큰
단계가 꼬리를 만드는 단계와 일치하지 않을 수 있으므로---예컨대 평소에는 저렴하지만 타일
예산을 간헐적으로 초과하는 rasteriser---귀속은 가장 느린 프레임들에 대해 계산한다.}
\label{tab:frame-budget-stages}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
설정 & 표면 & 정사영 & 방향 & rasteriser & 총 $p_{95}$ & 헤드룸 \\
 & (ms) & (ms) & (ms) & (ms) & (ms) & ($\times$) \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "frame_budget_stages", body,
           source="results/research_questions.json", measured=bool(cfgs))


def table_surface_source(res: dict, out: Path) -> None:
    """Layer 1: the same representation on surfaces from different sources."""
    d = _get(res, "comparison", "layer1", "data", default={}) or {}
    per = d.get("per_source") or {}

    def c(src: str, field: str, spec: str = ".3f") -> str:
        return _fmt(_get(per, src, field), spec)

    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{층위 1: 표면 공급원을 교체하고 표현 \emph{{과}} 지표는 고정한 비교
(제 \ref{{sec:external-baselines}}절). \texttt{{staircase}}는 mask에서 유도한 부호
거리장의 영등위면 양자화 정도이며, 정사영 저하가 관측될 경우 그 원인을 지목한다.}}
\label{{tab:layer1-source}}
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
표면 공급원 & Dice & $\Esurf$ (mm) & PSNR$_{{\mathrm{{ROI}}}}$ (dB)
  & eikonal & staircase \\
\midrule
Chan--Vese (제안) & {c('chan-vese','dice')} & {c('chan-vese','e_surf_mm','.3f')}
  & {c('chan-vese','psnr_roi_db','.2f')} & {c('chan-vese','sdf/eikonal_abs_mean')}
  & {c('chan-vese','sdf/staircase_index')} \\
외부 mask $\to$ SDF & {c('mask','dice')} & {c('mask','e_surf_mm','.3f')}
  & {c('mask','psnr_roi_db','.2f')} & {c('mask','sdf/eikonal_abs_mean')}
  & {c('mask','sdf/staircase_index')} \\
oracle (정확한 표면) & {c('oracle','dice')} & {c('oracle','e_surf_mm','.3f')}
  & {c('oracle','psnr_roi_db','.2f')} & {c('oracle','sdf/eikonal_abs_mean')}
  & {c('oracle','sdf/staircase_index')} \\
\midrule
spacing-aware 해제 & {c('chan-vese-no-spacing','dice')}
  & {c('chan-vese-no-spacing','e_surf_mm','.3f')}
  & {c('chan-vese-no-spacing','psnr_roi_db','.2f')}
  & {c('chan-vese-no-spacing','sdf/eikonal_abs_mean')}
  & {c('chan-vese-no-spacing','sdf/staircase_index')} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    _write(out, "layer1_source", body, source="results/comparison.json",
           measured=bool(per))


def table_free_geometry(res: dict, out: Path) -> None:
    """Layer 2: what pinning the geometry to the surface costs and buys."""
    d = _get(res, "comparison", "layer2", "data", default={}) or {}
    per = d.get("per_method") or {}

    def c(m: str, field: str, spec: str = ".3f") -> str:
        return _fmt(_get(per, m, field), spec)

    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{층위 2: 기하를 표면에 고정하는 것의 대가와 이득. 광도 지표와 기하 지표를
\emph{{반드시}} 함께 읽어야 한다. 자유 기하는 PSNR에서 이기고 $\Esurf$에서 크게
지도록 설계상 예상되며, 그 상충이 본 논문의 논점이다.}}
\label{{tab:layer2-free}}
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
표현 & PSNR$_{{\mathrm{{ROI}}}}$ (dB) & $\Esurf$ (mm) & 법선 오차 ($^\circ$)
  & 프레임당 바이트 & 기하 고정 \\
\midrule
CV-Dyn2DGS (2D 원반) & {c('cv-dyn2dgs','psnr_roi_db','.2f')}
  & {c('cv-dyn2dgs','e_surf_mm','.3f')} & {c('cv-dyn2dgs','normal_mean_deg','.2f')}
  & {c('cv-dyn2dgs','bytes_per_frame','.0f')} & 예 \\
Gaussian surfel (z-scale $\to0$) & {c('gaussian-surfel-exact','psnr_roi_db','.2f')}
  & {c('gaussian-surfel-exact','e_surf_mm','.3f')}
  & {c('gaussian-surfel-exact','normal_mean_deg','.2f')}
  & {c('gaussian-surfel-exact','bytes_per_frame','.0f')} & 예 \\
thin-3DGS ($\rho=0.1$) & {c('thin-3dgs','psnr_roi_db','.2f')}
  & {c('thin-3dgs','e_surf_mm','.3f')} & {c('thin-3dgs','normal_mean_deg','.2f')}
  & {c('thin-3dgs','bytes_per_frame','.0f')} & 예 \\
자유 3DGS (표면 초기화) & {c('free-3dgs-surface','psnr_roi_db','.2f')}
  & {c('free-3dgs-surface','e_surf_mm','.3f')}
  & {c('free-3dgs-surface','normal_mean_deg','.2f')}
  & {c('free-3dgs-surface','bytes_per_frame','.0f')} & \textbf{{아니오}} \\
자유 3DGS (무작위 초기화) & {c('free-3dgs-bbox_random','psnr_roi_db','.2f')}
  & {c('free-3dgs-bbox_random','e_surf_mm','.3f')}
  & {c('free-3dgs-bbox_random','normal_mean_deg','.2f')}
  & {c('free-3dgs-bbox_random','bytes_per_frame','.0f')} & \textbf{{아니오}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    _write(out, "layer2_free_geometry", body, source="results/comparison.json",
           measured=bool(per))


def table_viewpoint(res: dict, out: Path) -> None:
    """Layer 4: storage against viewpoint count, including the video competitor."""
    d = _get(res, "comparison", "layer4", "data", default={}) or {}
    rows = d.get("rows") or []
    be = d.get("breakeven")

    nm = r"\NM"
    eol = r" \\"

    def row(v: int) -> str:
        match = next((r for r in rows if int(r.get("viewpoints", -1)) == v), None)
        if match is None:
            return f"{v} & {nm} & {nm} & {nm} & {nm}{eol}"
        winner = match.get("winner") or nm
        return (
            f"{v} & {_fmt(match.get('ours_mb'), '.2f')} & "
            f"{_fmt(match.get('video_mb'), '.2f')} & "
            f"{_fmt(match.get('raw_volume_mb'), '.1f')} & "
            f"{winner}{eol}"
        )

    lines = "\n".join(row(v) for v in (1, 2, 4, 8, 16, 32))
    body = rf"""\begin{{table}}[htbp]
\centering\small
\caption{{층위 4: 시점 수에 따른 저장량. 본 방법은 시점 수에 대해 \emph{{평탄}}하고
사전렌더링 비디오는 선형으로 증가한다. 손익분기 시점 수가 ``자유 시점이 필요할 때
이긴다''는 진술을 주장에서 측정값으로 바꾼다. 비디오 비트레이트는 실측이거나 명시된
가정이며, 기본값은 제공되지 않는다.}}
\label{{tab:layer4-viewpoint}}
\begin{{tabular}}{{@{{}}rrrrl@{{}}}}
\toprule
시점 수 & 본 방법 (MB) & 비디오 (MB) & 원본 볼륨 (MB) & 우세 \\
\midrule
{lines}
\midrule
손익분기 시점 수 & \multicolumn{{4}}{{l}}{{{_fmt(be, '.2f')}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    _write(out, "layer4_viewpoint", body, source="results/comparison.json",
           measured=bool(rows))


def table_external_status(res: dict, out: Path) -> None:
    """Which external comparisons exist, and which have actually been run.

    Generated from ``external/manifest.json`` so the table cannot drift from the pins,
    and marked measured only when a results file says a target was really executed.
    """
    manifest = Path(__file__).resolve().parent.parent / "external" / "manifest.json"
    targets: list[dict] = []
    if manifest.exists():
        targets = json.loads(manifest.read_text(encoding="utf-8")).get("targets", [])
    ran = _get(res, "comparison", "external", "data", "ran", default={}) or {}

    lines = []
    dagger = r"$\dagger$"
    for t in sorted(targets, key=lambda x: (x["layer"], x["key"])):
        code = "---" if not t.get("repo") else (
            t["commit"][:8] if t.get("commit") else "---"
        )
        vend = "" if t.get("redistributable") else dagger
        status = "실행됨" if t["key"] in ran else r"\NM"
        key = t["key"].replace("_", "\\_")
        layer = t["layer"]
        lines.append(
            "%d & \\texttt{%s}%s & \\texttt{%s} & %s \\\\" % (layer, key, vend, code, status)
        )

    body = r"""\begin{table}[htbp]
\centering\small
\caption{외부 비교군의 고정 commit과 실행 상태. commit은
\texttt{external/manifest.json}에서 자동 생성되므로 표와 고정값이 어긋날 수 없다.
$\dagger$는 라이선스상 본 저장소에 포함할 수 없는 대상(라이선스 파일이 없거나
Inria/MPII 연구 전용)이며, 고정 commit으로 필요할 때만 clone한다.}
\label{tab:external-status}
\begin{tabular}{@{}clll@{}}
\toprule
층위 & 대상 & 고정 commit & 상태 \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _write(out, "external_status", body, source="external/manifest.json",
           measured=bool(ran))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("results", nargs="?", default="results",
                    help="directory written by `cvdyn2dgs experiments`")
    ap.add_argument("tables", nargs="?", default="paper/tables",
                    help="output directory for the .tex tables")
    args = ap.parse_args(argv)

    res_dir = Path(args.results)
    out_dir = Path(args.tables)
    out_dir.mkdir(parents=True, exist_ok=True)

    res: dict = {}
    combined = res_dir / "all_results.json"
    if combined.exists():
        res = json.loads(combined.read_text(encoding="utf-8"))
        print(f"loaded {combined}")
    else:
        # Fall back to individual files so partial runs still fill what they can.
        for key, fname in (
            ("theory_checks", "theory_checks.json"),
            ("baselines", "baselines.json"),
            ("research_questions", "research_questions.json"),
            ("ablations", "ablations.json"),
            ("spacing_ablation", "spacing_ablation.json"),
            ("progressive", "progressive.json"),
        ):
            p = res_dir / fname
            if p.exists():
                loaded = json.loads(p.read_text(encoding="utf-8"))
                if key == "baselines" and isinstance(loaded, dict):
                    loaded = loaded.get("headline", loaded)
                res[key] = loaded
                print(f"loaded {p}")
        if not res:
            print(f"no results found in {res_dir} -- writing stub tables", file=sys.stderr)

    print(f"writing tables to {out_dir}")
    table_kernel_checks(res, out_dir)
    table_theory_rates(res, out_dir)
    table_rq1(res, out_dir)
    table_rq2(res, out_dir)
    table_rq3(res, out_dir)
    table_rq4(res, out_dir)
    table_rq5(res, out_dir)
    table_rq6(res, out_dir)
    table_baselines(res, out_dir)
    table_ablations(res, out_dir)
    table_stages(res, out_dir)
    # External comparison design (paper sec. 7.3). These are stubs until someone with a
    # GPU actually runs the comparisons; external_status is generated from the manifest
    # so its commit column is always correct even when nothing has been run.
    table_surface_source(res, out_dir)
    table_free_geometry(res, out_dir)
    table_viewpoint(res, out_dir)
    table_external_status(res, out_dir)
    # Quality against cost. These are the two tables that answer "what did it cost to get
    # that quality, and is the trade-off real or is this configuration just worse?"
    table_cost_quality(res, out_dir)
    table_frame_budget_stages(res, out_dir)

    if not res:
        print(
            "\nAll tables except kernel_checks are stubs. Produce measurements with:\n"
            "  cvdyn2dgs experiments --out results --size small\n"
            "then re-run this script.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
